version: '3.8'

services:
  promocodefactory.webhost:
    image: myapp
    build:
      context: .
      dockerfile: PromoCodeFactory.WebHost/Dockerfile
    ports:
      - "5003:8080"
      - "5004:8081"
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=promocode_factory_db;Username=postgres;Password=docker;
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: promocode_factory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge